apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: github-deployer
  namespace: test
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: github-deployer
subjects:
- apiGroup: rbac.authorization.k8s.io
  kind: User
  name: github-deployer
