deployment:
  additionalVolumes:
    - name: persistence
      hostPath:
        path: /opt/data/traefik
        type: DirectoryOrCreate
additionalVolumeMounts:
  - name: persistence
    mountPath: /opt/data
logs:
  general:
    level: ERROR
  access:
    enabled: true
    filePath: "/opt/data/access.log"
additionalArguments:
  - "--api.insecure=true"
  - "--entrypoints.web.http.redirections.entryPoint.to=websecure"
  - "--log.filePath=/opt/data/traefik.log"
env:
  - name: TZ
    value: Asia/Shanghai
#   - name: ALICLOUD_ACCESS_KEY
#     value: LTAI569DEStwwuHP4HW
#   - name: ALICLOUD_SECRET_KEY
#     value: xuOfzVsJFwKSgCGpP7Qt
# certResolvers:
#   jet:
#     email: certificate-applicant@cdyoue.onaliyun.com
#     dnsChallenge:
#       provider: alidns
#       delayBeforeCheck: 30
#       resolvers:
#         - 1.1.1.1
#         - 8.8.8.8
#     storage: /opt/data/acme.json
ports:
  web:
    port: 8000
    expose: true
    exposedPort: 80
    protocol: TCP
    nodePort: 80
    forwardedHeaders:
      insecure: true
  websecure:
    port: 8443
    expose: true
    exposedPort: 443
    protocol: TCP
    nodePort: 10443
    forwardedHeaders:
      insecure: true
    proxyProtocol:
      insecure: true
#     tls:
#       enabled: true
#       certResolver: "jet"
service:
  type: LoadBalancer
  externalIPs: []
resources: {}
affinity: {}
nodeSelector: {}
tolerations: []
