apiVersion: kubeadm.k8s.io/v1beta3
kind: ClusterConfiguration
clusterName: kubernetes
kubernetesVersion: 1.26.5
controlPlaneEndpoint: 172.24.11.137:6443
imageRepository: registry.aliyuncs.com/google_containers
apiServer:
  extraArgs:
    service-node-port-range: "80-32767"
  certSANs:
  - 172.24.11.137
networking:
  podSubnet: 10.244.0.0/16
  serviceSubnet: 10.10.0.0/16
---
apiVersion: kubeproxy.config.k8s.io/v1alpha1
kind: KubeProxyConfiguration
mode: ipvs
